## NAME GITHUB ACTION WORKFLOW
name: STIG Parser CI/CD

## RUN WORKFLOW WHEN
on:
  ## PR TO DEV
  pull_request:
    branches: [ master ]
  
  ## ALLOW FOR MANUAL EXECUTION
  workflow_dispatch:

## DEFINE WORKFLOW
jobs:   
  ## DEFINE BUILD JOB
  build-publish:
    ## DEFINE NAME
    name: "Build & Publish"

    ## WAIT FOR TEST JOB
    needs: test

    ## DEFINE WORKER
    runs-on: ubuntu-latest

    ## DEFINE STEPS
    steps:
      ## CLONE REPO CODE
      - uses: actions/checkout@v2

      ## SETUP PYTHON3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      ## CONFIGURE WORKER TO PUBLISH PACKAGE
      - name: "Install Dependencies"
        run: |
          # Upgrade pip
          python3 -m pip install --upgrade pip
          # Install Dependencies
          python3 -m pip install --upgrade build xmltodict

      ## BUILD PACKAGE
      - name: "Build Python Package"
        run: |
          # Build Python Package
          python3 -m build

      ## PUBLISH PACKAGE TO TESTPYPI
      - name: "Publish Package to Test PyPi"
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}